import { memo, useState, useCallback } from 'react';
import { usePwaIconGenerator } from '../hooks/usePwaIconGenerator';
import { useManifestGenerator } from '../hooks/useManifestGenerator';
import IconGridPreview from './IconGridPreview';
import ManifestPreview from './ManifestPreview';

interface PWAExportPanelProps {
  emoji: string;
  font?: string;
}

// Note: the apple-touch-icon referenced here is generated by the favicon pack above.
// Users can also rename icon-192.png to apple-touch-icon.png if only using the PWA pack.
const PWA_HTML_SNIPPET = `<link rel="manifest" href="/manifest.json">
<meta name="theme-color" content="#0ea5e9">
<link rel="apple-touch-icon" href="/apple-touch-icon.png">`;

const INSTALL_STEPS = [
  { label: 'Generate icons', detail: 'Click "Download PWA Icon Pack" below.' },
  { label: 'Unzip & copy files', detail: 'Drop icons + manifest.json into your project root (or public/).' },
  { label: 'Add manifest link', detail: 'Paste the HTML snippet below into your <head>.' },
  { label: 'Deploy', detail: 'Serve over HTTPS — your app is now installable! 🎉' },
];

function PWAExportPanel({ emoji, font }: PWAExportPanelProps) {
  const { generating, downloadPwaPack } = usePwaIconGenerator(emoji, font);
  const { downloadManifest } = useManifestGenerator();
  const [copied, setCopied] = useState(false);

  const handleCopyHtml = useCallback(async () => {
    try {
      await navigator.clipboard.writeText(PWA_HTML_SNIPPET);
    } catch {
      // Fallback for non-secure contexts (HTTP) where Clipboard API is unavailable.
      // execCommand is deprecated but remains the only option in those environments.
      const ta = document.createElement('textarea');
      ta.value = PWA_HTML_SNIPPET;
      document.body.appendChild(ta);
      ta.select();
      // eslint-disable-next-line @typescript-eslint/no-deprecated
      document.execCommand('copy');
      document.body.removeChild(ta);
    }
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  }, []);

  return (
    <div className="pwa-panel">
      {/* ── Preview ─────────────────────────────────────────── */}
      <div className="pwa-preview-card">
        <h2 className="section-title">PWA Icon Preview</h2>
        <IconGridPreview emoji={emoji} font={font} />
      </div>

      {/* ── Export ──────────────────────────────────────────── */}
      <div className="pwa-export-card">
        <h2 className="section-title">PWA Export</h2>

        {/* Readiness checklist */}
        <div className="pwa-checklist">
          <div className="pwa-check-item pwa-check-pass">✅ 192×192 icon ready</div>
          <div className="pwa-check-item pwa-check-pass">✅ 512×512 icon ready</div>
          <div className="pwa-check-item pwa-check-pass">✅ manifest.json ready</div>
          <div className="pwa-check-item pwa-check-info">🛡️ Maskable icons included</div>
        </div>

        {/* Download buttons */}
        <div className="pwa-download-actions">
          <button
            className="btn btn-primary btn-full"
            onClick={downloadPwaPack}
            disabled={generating}
          >
            {generating ? '⏳ Generating…' : '📱 Download PWA Icon Pack (ZIP)'}
          </button>
          <button className="btn btn-secondary btn-full" onClick={downloadManifest}>
            📄 Download manifest.json
          </button>
        </div>

        {/* Home screen mock */}
        <div className="home-screen-mock">
          <div className="mock-phone">
            <div className="mock-status-bar" />
            <div className="mock-icons-grid">
              <div className="mock-icon-slot mock-icon-active">
                <span className="mock-icon-emoji">{emoji}</span>
                <span className="mock-app-label">My App</span>
              </div>
              <div className="mock-icon-slot mock-icon-dim" />
              <div className="mock-icon-slot mock-icon-dim" />
              <div className="mock-icon-slot mock-icon-dim" />
            </div>
          </div>
          <p className="mock-caption">Home screen preview</p>
        </div>

        {/* Manifest preview */}
        <ManifestPreview />

        {/* HTML snippet */}
        <div className="html-snippet-section">
          <div className="snippet-header">
            <span className="snippet-title">HTML &lt;head&gt; tags</span>
            <button className="btn btn-ghost btn-sm" onClick={handleCopyHtml}>
              {copied ? '✓ Copied!' : '📋 Copy'}
            </button>
          </div>
          <pre className="code-block">{PWA_HTML_SNIPPET}</pre>
        </div>

        {/* Install guide */}
        <div className="pwa-install-guide">
          <h3 className="pwa-subsection-title">Make your site installable in 4 steps</h3>
          <div className="steps-list">
            {INSTALL_STEPS.map((step, i) => (
              <div key={i} className="step-item">
                <h4 className="step-title">{i + 1}. {step.label}</h4>
                <p className="step-content">{step.detail}</p>
              </div>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
}

export default memo(PWAExportPanel);
