export interface EmojiCategory {
  name: string;
  emojis: string[];
}

export const EMOJI_CATEGORIES: EmojiCategory[] = [
  {
    name: 'Smileys & Emotion',
    emojis: [
      '😀', '😃', '😄', '😁', '😆', '😅', '😂', '🤣', '😊', '😇',
      '🙂', '🙃', '😉', '😌', '😍', '🥰', '🤩', '😘', '😗', '😙',
      '😋', '😛', '😜', '🤪', '🤔', '🤗', '😐', '😑', '😏', '🙄',
      '😬', '😔', '😪', '😴', '😷', '🤒', '🤕', '🤢', '🤮', '🥴',
      '😵', '🤯', '😎', '🤓', '🧐', '😕', '😟', '🙁', '😮', '😲',
      '😳', '🥺', '😢', '😭', '😱', '😖', '😣', '😞', '😓', '😩',
      '😫', '😤', '😠', '😡', '🤬', '💀', '😈', '👿', '🤡', '👹',
      '👺', '👻', '💩', '🫠', '🥹', '🫡', '🫥',
    ],
  },
  {
    name: 'People & Body',
    emojis: [
      '👋', '🤚', '🖐️', '✋', '🖖', '👌', '🤌', '🤏', '✌️', '🤞',
      '🤟', '🤘', '🤙', '👈', '👉', '👆', '🖕', '👇', '☝️', '👍',
      '👎', '✊', '👊', '🤛', '🤜', '👏', '🙌', '👐', '🤲', '🤝',
      '🙏', '💪', '🦾', '🦿', '🦵', '🦶', '👂', '🦻', '👃', '🫀',
      '🫁', '🧠', '🦷', '🦴', '👀', '👁️', '👅', '👄', '🫦', '💋',
      '👶', '🧒', '👦', '👧', '🧑', '👱', '👨', '🧔', '👩', '🧓',
      '👴', '👵', '🧑‍⚕️', '🧑‍🎓', '🧑‍🏫', '🧑‍💻', '🧑‍🎨', '🧑‍🚀', '🧙', '🧚',
      '🧛', '🧜', '🧝', '🧞', '🧟', '🧌',
    ],
  },
  {
    name: 'Animals & Nature',
    emojis: [
      '🐶', '🐱', '🐭', '🐹', '🐰', '🦊', '🐻', '🐼', '🐨', '🐯',
      '🦁', '🐮', '🐷', '🐸', '🐵', '🙈', '🙉', '🙊', '🐔', '🐧',
      '🐦', '🦆', '🦅', '🦉', '🦇', '🐺', '🐗', '🐴', '🦄', '🐝',
      '🐛', '🦋', '🐌', '🐞', '🐜', '🦟', '🦗', '🕷️', '🦂', '🐢',
      '🐍', '🦎', '🦕', '🦖', '🐊', '🦈', '🐳', '🐬', '🦭', '🐟',
      '🐠', '🐡', '🦑', '🐙', '🦐', '🦞', '🦀', '🐡', '🐆', '🐘',
      '🦏', '🦛', '🦒', '🦓', '🦍', '🦧', '🐿️', '🦔', '🌿', '🌱',
      '🌲', '🌳', '🌴', '🎋', '🍀', '🌺', '🌸', '🌼', '🌻', '🌹',
      '🌈', '⛅', '🌤️', '🌧️', '⛈️', '🌩️', '❄️', '🔥', '🌊', '🌙',
    ],
  },
  {
    name: 'Food & Drink',
    emojis: [
      '🍎', '🍊', '🍋', '🍇', '🍓', '🫐', '🍒', '🍑', '🥭', '🍍',
      '🥥', '🥝', '🍅', '🥑', '🍆', '🥕', '🌽', '🌶️', '🥦', '🧅',
      '🍄', '🥜', '🫘', '🍞', '🥐', '🥨', '🧀', '🥚', '🍳', '🥞',
      '🧇', '🥓', '🥩', '🍗', '🍖', '🌭', '🍔', '🍟', '🍕', '🫓',
      '🌮', '🌯', '🫔', '🥙', '🧆', '🥚', '🍱', '🍘', '🍙', '🍚',
      '🍛', '🍜', '🍝', '🍠', '🍢', '🍣', '🍤', '🍥', '🧁', '🎂',
      '🍰', '🍮', '🍭', '🍬', '🍫', '🍿', '🍩', '🍪', '🌰', '🍦',
      '🍧', '🍨', '🥤', '☕', '🍵', '🫖', '🧃', '🧊', '🍺', '🍻',
      '🥂', '🍷', '🥃', '🍸', '🍹', '🧋',
    ],
  },
  {
    name: 'Travel & Places',
    emojis: [
      '🚗', '🚕', '🚙', '🚌', '🚎', '🏎️', '🚓', '🚑', '🚒', '🚐',
      '🛻', '🚚', '🚛', '🚜', '🏍️', '🛵', '🛺', '🚲', '🛴', '🛹',
      '🚁', '✈️', '🛩️', '🛫', '🛬', '🚀', '🛸', '🚢', '⛵', '🛥️',
      '🚂', '🚃', '🚄', '🚅', '🚆', '🚇', '🚊', '🚉', '🚍', '🛻',
      '⛺', '🏕️', '🏖️', '🏜️', '🏝️', '🏞️', '🏟️', '🏛️', '🏗️', '🏘️',
      '🏚️', '🏠', '🏡', '🏢', '🏣', '🏤', '🏥', '🏦', '🏨', '🏩',
      '🏪', '🏫', '🏬', '🏭', '🏯', '🏰', '🗼', '🗽', '🗾', '🎑',
      '🌋', '🏔️', '🗻', '🌄', '🌅', '🌇', '🌆', '🏙️', '🌃', '🌉',
      '⛩️', '🛕', '⛪', '🕌', '🕍', '🕋', '⛲', '⛺',
    ],
  },
  {
    name: 'Activities',
    emojis: [
      '⚽', '🏀', '🏈', '⚾', '🥎', '🎾', '🏐', '🏉', '🥏', '🎱',
      '🏓', '🏸', '🏒', '🏑', '🥍', '🏏', '🪃', '🥅', '⛳', '🪁',
      '🎣', '🤿', '🥊', '🥋', '🎽', '🛹', '🛷', '⛸️', '🤸', '⛷️',
      '🏂', '🪂', '🏋️', '🤼', '🤺', '🏇', '⛹️', '🏊', '🚣', '🧗',
      '🚵', '🚴', '🤾', '🏌️', '🏄', '🏇', '🧘', '🛀', '🎯', '🎱',
      '🎰', '🎲', '🧩', '♟️', '🪀', '🪁', '🎭', '🎨', '🎬', '🎤',
      '🎧', '🎼', '🎵', '🎶', '🎸', '🎹', '🥁', '🎷', '🎺', '🎻',
      '🪗', '🎮', '🕹️', '🎪', '🎠', '🎡', '🎢', '🎟️', '🎫',
    ],
  },
  {
    name: 'Objects',
    emojis: [
      '⌚', '📱', '💻', '⌨️', '🖥️', '🖨️', '🖱️', '🖲️', '💾', '💿',
      '📀', '🧮', '📷', '📸', '📹', '🎥', '📽️', '📞', '☎️', '📟',
      '📠', '📺', '📻', '🎙️', '🎚️', '🎛️', '🧭', '⏱️', '⏲️', '🕰️',
      '⌛', '⏳', '📡', '🔋', '🔌', '💡', '🔦', '🕯️', '🪔', '🧱',
      '💰', '💳', '💎', '⚖️', '🔧', '🔨', '⚒️', '🛠️', '⛏️', '🔩',
      '🗜️', '🔑', '🗝️', '🔒', '🔓', '🚪', '🪑', '🛋️', '🛏️', '🚽',
      '🪠', '🚿', '🛁', '🪥', '🪒', '🧴', '🧷', '🧹', '🧺', '🧻',
      '🪣', '🧼', '🫧', '🏺', '🔮', '💈', '🧲', '🪄', '🧪', '🧫',
      '🧬', '🔭', '🔬', '🩺', '🩹', '💊', '💉', '🩸', '🧯', '🔥',
      '🪓', '🗡️', '🛡️', '🚬', '⚰️', '⚱️', '🏮', '📿', '💌',
    ],
  },
  {
    name: 'Symbols',
    emojis: [
      '❤️', '🧡', '💛', '💚', '💙', '💜', '🖤', '🤍', '🤎', '💔',
      '❣️', '💕', '💞', '💓', '💗', '💖', '💘', '💝', '💟', '☮️',
      '✝️', '☪️', '🕉️', '✡️', '🔯', '☯️', '☦️', '🛐', '⛎', '♈',
      '♉', '♊', '♋', '♌', '♍', '♎', '♏', '♐', '♑', '♒',
      '♓', '⭕', '✅', '☑️', '✔️', '❌', '❎', '➕', '➖', '➗',
      '✖️', '💲', '💱', '™️', '©️', '®️', '〰️', '➰', '➿', '🔚',
      '🔙', '🔛', '🔝', '🔜', '🔃', '🔀', '🔁', '🔂', '▶️', '⏩',
      '⏭️', '⏯️', '◀️', '⏪', '⏮️', '🔼', '⏫', '🔽', '⏬', '⏸️',
      '⏹️', '⏺️', '🎦', '🔅', '🔆', '📶', '📳', '📴', '♻️', '🔱',
      '📛', '🔰', '⭐', '🌟', '💫', '✨', '🎉', '🎊', '🎈', '☀️',
      '🌙', '⚡', '🌈', '❄️', '⚠️', '🚫', '✨', '🔔', '🔕', '🎵',
      '🔇', '📢', '📣', '💬', '💭', '💯', '🔞', '🆚', '🆘', '❓',
    ],
  },
];

export const ALL_EMOJIS: string[] = EMOJI_CATEGORIES.flatMap((cat) => cat.emojis);

/**
 * Map of emoji character → space-separated search keywords (all lowercase).
 * Emojis without an entry are searchable only via their category name.
 */
export const EMOJI_KEYWORDS: Record<string, string> = {
  // Smileys & Emotion
  '😀': 'grinning smile happy face',
  '😂': 'joy laugh crying tears',
  '🤣': 'rolling laughing',
  '😊': 'smile blush happy',
  '😍': 'heart eyes love',
  '🥰': 'love hearts smiling',
  '🤩': 'star struck excited',
  '😘': 'kiss wink',
  '😎': 'sunglasses cool',
  '🤔': 'thinking',
  '😴': 'sleeping tired',
  '😷': 'mask sick',
  '🤒': 'sick ill thermometer',
  '🤯': 'exploding head mind blown',
  '😢': 'crying sad tears',
  '😭': 'loudly crying sob',
  '😱': 'scream fear scared',
  '😡': 'angry red mad',
  '🤬': 'swearing angry',
  '💀': 'skull death',
  '😈': 'devil evil',
  '👻': 'ghost',
  '💩': 'poop pile',
  '🤡': 'clown',

  // People & Body
  '👋': 'wave hello goodbye',
  '👍': 'thumbs up like ok',
  '👎': 'thumbs down dislike',
  '👏': 'clap applause',
  '🙏': 'pray please thanks',
  '💪': 'muscle strong flex bicep',
  '🧠': 'brain mind',
  '👀': 'eyes look see',
  '👄': 'mouth lips',
  '👶': 'baby',
  '👦': 'boy',
  '👧': 'girl',
  '👨': 'man',
  '👩': 'woman',
  '🧙': 'wizard mage',
  '🧛': 'vampire',

  // Animals & Nature
  '🐶': 'dog puppy',
  '🐱': 'cat kitten',
  '🐭': 'mouse',
  '🐹': 'hamster',
  '🐰': 'rabbit bunny',
  '🦊': 'fox',
  '🐻': 'bear',
  '🐼': 'panda',
  '🐨': 'koala',
  '🐯': 'tiger',
  '🦁': 'lion',
  '🐮': 'cow',
  '🐷': 'pig',
  '🐸': 'frog',
  '🐵': 'monkey',
  '🐔': 'chicken',
  '🐧': 'penguin',
  '🦆': 'duck',
  '🦅': 'eagle',
  '🦉': 'owl',
  '🐺': 'wolf',
  '🦋': 'butterfly',
  '🐛': 'bug worm caterpillar',
  '🐝': 'bee',
  '🐞': 'ladybug ladybird',
  '🦄': 'unicorn',
  '🐉': 'dragon',
  '🦕': 'dinosaur sauropod',
  '🦖': 'dinosaur rex',
  '🐳': 'whale',
  '🐬': 'dolphin',
  '🦈': 'shark',
  '🐙': 'octopus',
  '🐠': 'tropical fish',
  '🌿': 'herb plant',
  '🍀': 'clover lucky',
  '🌺': 'flower hibiscus',
  '🌸': 'cherry blossom flower',
  '🌼': 'flower blossom',
  '🌻': 'sunflower',
  '🌹': 'rose flower',
  '🌈': 'rainbow',
  '❄️': 'snowflake cold ice',
  '🔥': 'fire flame hot',
  '🌊': 'wave water ocean',
  '🌙': 'moon night',
  '☀️': 'sun sunny',
  '⛅': 'cloud sun partly',

  // Food & Drink
  '🍎': 'apple fruit red',
  '🍊': 'orange tangerine fruit',
  '🍋': 'lemon fruit',
  '🍇': 'grapes fruit',
  '🍓': 'strawberry fruit',
  '🍒': 'cherry fruit',
  '🍑': 'peach fruit',
  '🥝': 'kiwi fruit',
  '🥑': 'avocado',
  '🍕': 'pizza',
  '🍔': 'burger hamburger',
  '🍟': 'fries chips',
  '🌮': 'taco mexican',
  '🍣': 'sushi japanese',
  '🍜': 'noodles ramen',
  '🎂': 'birthday cake',
  '🍰': 'cake slice',
  '🍪': 'cookie biscuit',
  '🍩': 'donut doughnut',
  '🍺': 'beer',
  '🍷': 'wine red',
  '☕': 'coffee hot',
  '🍵': 'tea hot',
  '🧃': 'juice drink',
  '🥤': 'cup drink',
  '🧋': 'bubble tea boba',

  // Travel & Places
  '🚗': 'car automobile',
  '✈️': 'airplane plane flight',
  '🚀': 'rocket space launch',
  '🛸': 'ufo flying saucer',
  '🚢': 'ship cruise',
  '🚂': 'train locomotive',
  '🚁': 'helicopter',
  '🏖️': 'beach sand summer',
  '🏔️': 'mountain snow',
  '🏠': 'house home',
  '🏢': 'office building',
  '🗼': 'tokyo tower',
  '🗽': 'statue liberty',
  '⛩️': 'shrine japan torii',
  '🏰': 'castle',
  '🌋': 'volcano',
  '🌄': 'sunrise mountain',

  // Activities
  '⚽': 'soccer football',
  '🏀': 'basketball',
  '🏈': 'american football',
  '⚾': 'baseball',
  '🎾': 'tennis',
  '🎸': 'guitar music',
  '🎹': 'piano keyboard music',
  '🥁': 'drum music',
  '🎷': 'saxophone music',
  '🎺': 'trumpet music',
  '🎻': 'violin music',
  '🎮': 'game controller video',
  '🕹️': 'joystick game',
  '🎲': 'dice game',
  '🧩': 'puzzle jigsaw',
  '🎨': 'art palette paint',
  '🎭': 'theater masks art',
  '🎬': 'film movie clapper',
  '🎤': 'microphone sing',
  '🎧': 'headphones music',
  '🎯': 'target dart bullseye',
  '🎉': 'party celebration',
  '🎊': 'confetti party',
  '🎪': 'circus tent',
  '🏆': 'trophy winner',

  // Objects
  '💻': 'laptop computer',
  '📱': 'phone mobile',
  '⌨️': 'keyboard',
  '🖥️': 'desktop computer monitor',
  '📷': 'camera photo',
  '📺': 'tv television',
  '📻': 'radio',
  '💡': 'lightbulb idea',
  '🔦': 'flashlight torch',
  '💰': 'money bag cash',
  '💎': 'gem diamond jewel',
  '🔑': 'key',
  '🗝️': 'key old',
  '🔒': 'lock locked',
  '🔧': 'wrench tool',
  '🔨': 'hammer tool',
  '⚒️': 'tools hammer',
  '🛠️': 'tools',
  '🔮': 'crystal ball magic',
  '🧲': 'magnet',
  '🧪': 'test tube science',
  '🧫': 'petri dish science',
  '🧬': 'dna science',
  '🔭': 'telescope science',
  '🔬': 'microscope science',
  '🏺': 'amphora',
  '⚓': 'anchor ship',
  '🎁': 'gift present',

  // Symbols
  '❤️': 'heart love red',
  '🧡': 'heart orange love',
  '💛': 'heart yellow love',
  '💚': 'heart green love',
  '💙': 'heart blue love',
  '💜': 'heart purple love',
  '🖤': 'heart black love',
  '🤍': 'heart white love',
  '💔': 'broken heart',
  '⭐': 'star',
  '🌟': 'star glowing',
  '💫': 'star dizzy',
  '✨': 'sparkles shine',
  '⚡': 'lightning electric bolt',
  '🎵': 'music note',
  '🎶': 'music notes',
  '♻️': 'recycle',
  '💯': 'hundred percent',
  '🔔': 'bell notification',
  '🚫': 'no prohibited',
  '⚠️': 'warning caution',
  '❓': 'question',
};

